version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Smoke test of glpsol
          command: ls -l & which glpsol & glpsol --version
      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up
      - run:
          name: Build Docker image
          command: |
# FIXME how should this be picked?
#            TAG=0.1.$CIRCLE_BUILD_NUM
            TAG=0.1.1
            docker build -t $DOCKERHUB_USERNAME/lp-bound-docker:$TAG .
      - run:
          name: Push application Docker image
          command: |
#            TAG=0.1.$CIRCLE_BUILD_NUM
            TAG=0.1.1
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/lp-bound-docker:$TAG
